### ISSUE TITLE
just-pick without undefined values

### ISSUE THREAD

**Issue by ilearnio** [angus-c/just#103]
Currently `just-pick` returns undefined values for not found keys. I'm not sure where this can be useful. For me it's basically always a problem.

In lodash it's done differently, it never returns undefined values. 

Maybe it makes sense to add a 3rd parameter that will allow to skip undefined values? Or maybe add a breaking change (new version) that will remove undefined values by default? That would be the best

**Comment by angus-c** [comment]
Breaking change suggestion is good. I'll get into it. Thanks for letting me know!

**Comment by angus-c** [comment]
Fixed in v2.0.0

**Comment by ilearnio** [comment]
That's fantastic! Many thanks! Closing
