### ISSUE TITLE
LICENSE file missing in npm package

### ISSUE THREAD

**Issue by char0n** [angus-c/just#107]
Hello, is it possible to incorporate the LICENSE file inside the npm package ? Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the npm package a lot of people cannot use it (technically, nobody can).

Thank you

**Comment by angus-c** [comment]
I didn't realize that. I thought it was sufficient for the LICENSE to appear in the root directory of the Github repo.

**Comment by char0n** [comment]
According to our legal and the license itself (MIT) it's not enough. MIT requires that the code is associated with the full license text when being distributed. NPM is a form of distribution and the code inside the npm package contains associated license text, so technically even by the terms of MIT license it's unclear how the code can be used without it.

Thank you

**Comment by angus-c** [comment]
Ok thanks for the info. I'll try to do this in the next couple of days. In the meantime you have my word it's ok to use the code as you please.

**Comment by angus-c** [comment]
Resolved. Bumped every package by a minor increment and included a LICENSE file in each

**Comment by char0n** [comment]
Thank you very much. I confirm the npm distribution now contains the license.
