### ISSUE TITLE
Capitalize replacement

### ISSUE THREAD

**Issue by antony** [angus-c/just#122]
I notice there is a lack of a capitalize package, similar to `capitalize` provided by lodash.

I'm using the pascal-case module for now, but it removes dashes where I don't want it to.

Would you be up for adding a capitalize package if I open a PR?

**Comment by angus-c** [comment]
Sure!

**Comment by bakkot** [comment]
Presumably fixed by #123?

**Comment by angus-c** [comment]
Yep!
