### ISSUE TITLE
typeOf(async () => {}) === 'asyncfunction'

### ISSUE THREAD

**Issue by ilearnio** [angus-c/just#124]
Just found a potential pitfall that caused a bug in out app. When passing an `async` function to `just-typeof` it returns `"asyncfunction"` but should return `"function"`, because there is no such type in ECMA specification.

See it in action:
https://runkit.com/artnikpro/5c781b9516d1d00012427b06

**Comment by angus-c** [comment]
Oh great catch! Will fix tonight.

**Comment by angus-c** [comment]
Should be fixed in just-typeof@2.0.0
