### ISSUE TITLE
Prettier, husky, lint-staged

### ISSUE THREAD

**Issue by jedmao** [angus-c/just#128]
Would you be open to introducing [Prettier](https://prettier.io/), [husky](https://www.npmjs.com/package/husky) and [lint-staged](https://www.npmjs.com/package/lint-staged) to ensure the code is formatted properly on every commit?

**Comment by angus-c** [comment]
Sure, I run prettier via VSCode but am open to having the commit hook to auto fix.

**Comment by jedmao** [comment]
To take it a step further, would you also be open to including a `.vscode` folder with a [recommended extensions list](https://github.com/jedmao/ts/blob/master/.vscode/extensions.json) and perhaps some workspace settings to [format on save](https://github.com/jedmao/ts/blob/master/.vscode/settings.json)?

**Comment by jedmao** [comment]
I should also add that Prettier extends EditorConfig out-of-the-box. A proper Prettier installation is to also install [`eslint-config-prettier`](https://www.npmjs.com/package/eslint-config-prettier):

> Turns off all rules that are unnecessary or might conflict with Prettier.

Which means we have to get rid of any "formatting" rules in eslint and let Prettier do its job.

I'm willing to do all this work. Just need to know what you're willing to support before I waste cycles.

**Comment by angus-c** [comment]
`.vscode folder`: No, I don't want any IDE specific code
`use eslint-config-prettier rules`: No I want to stick with the rules I have and use `eslint --fix` (via plugin)

**Comment by jedmao** [comment]
So you want to run `eslint --fix` _after_ Prettier? This is backwards, BTW. Just asking for clarity.

**Comment by jedmao** [comment]
I mean, one of the whole points of Prettier is to stop bikeshedding over opinionated formatting preferences.
> No need to discuss style in code review

**Comment by angus-c** [comment]
Prettier is just a wrapper around `eslint --fix`. You can use prettier's formatting suggestions or you can set your own in .eslintrc and use `eslint --fix`. The mechanism is identical. 

There is no bikeshedding because I created the .eslintrc

In VSCode I can emulate prettier behavior but using my own config via the `eslint.executeAutofix` setting.

**Comment by jedmao** [comment]
The [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier) is, yeah. That's one way of doing it.

**Comment by angus-c** [comment]
Not even. Just dbaeumer.vscode-eslint

**Comment by jedmao** [comment]
There are conflicts with certain rules you've defined in ESLint vs. Prettier. Just one example is the [`curly`](https://github.com/prettier/eslint-config-prettier#curly) rule.

> If you use the `"multi-line"` or `"multi-or-nest"` option, the rule can conflict with Prettier.

I'm sure there's more.

**Comment by angus-c** [comment]
It doesn't matter because I have no interest in using prettier's rules in this project.
