### ISSUE TITLE
just-is-empty says that the number 0 is empty

### ISSUE THREAD

**Issue by antony** [angus-c/just#132]
Not sure if this is desired behaviour or not, but I don't consider 0 to be empty.

What was the intention?

**Comment by angus-c** [comment]
I think I need to revisit this. Lodash isEmpty returns false for any non-enumerable (so all primitives too)

**Comment by angus-c** [comment]
Created just-is-empty@2.0.1 which follows the more conventional definition (e.g. that used by underscore, lodash):

- all primitives are now empty
- object, array, set, map are empty of no enumerable keys

I know this doesn't fix your issue (sorry!) but it alerted me to the inconsistent definition (thanks!)

Feel free to create a new issue for a new utility for what you need.
