### ISSUE TITLE
safe-get returning null if any parent property is null

### ISSUE THREAD

**Issue by amaldare93** [angus-c/just#148]
found some buggy behavior where if any value in a get path is falsey (null or 0), it will return that falsy value, instead (see below examples, first one is "correct", second two are "incorrect"

```js
const get = require('just-safe-get');

const obj = { a: { aa: undefined }};
get(obj, 'a.aa.aaa'); // undefined

const obj2 = { a: { aa: null }};
get(obj2, 'a.aa.aaa'); // null

const obj3 = { a: { aa: 0 }};
get(obj3, 'a.aa.aaa'); // 0
```

**Comment by angus-c** [comment]
Thanks for reporting! Should be fixed by `just-safe-get@1.3.2`
