### ISSUE TITLE
just-diff bug

### ISSUE THREAD

**Issue by davidhq** [angus-c/just#161]
Hi, thank you for great collection of utilities...

I found some issue in `just-diff` though ...

https://gist.github.com/davidhq/b8ecfa2a97e56789fcd6f70cb6776529

I tested a lot of other json diff generating libraries but would still like to use your method because, surprisingly, it performs the best of them all... 

Can you confirm this bug and possibly solve? If you don't have time currently, maybe I can investigate, but please first confirm.. and if you can fix it in a few minutes, then this is a better option than me trying and possibly breaking something else :)

thank you

**Comment by angus-c** [comment]
Hi! Good catch, this is probably because I'm doing an alpha sort instead of numeric for removed array keys. Weill try to get to it it this weekend

**Comment by davidhq** [comment]
Yes, that must be it... hopefully it can be easily solved :)
I agree, this was a great catch, because of it the playlists in [here](https://dmt-system.com) (a plug,in case you are interested)... became really weird.

I have another question if I may:
https://github.com/angus-c/just/blob/master/packages/collection-clone/index.js

How come this is approx 5x faster than usual alternatives like JSONstringifyparse or structuralClone  ?  I checked the code, it is simple ... so I'm not sure why articles like https://dassur.ma/things/deep-copy/ don't mention your kind of approach ?

**Comment by angus-c** [comment]
This should be fixed by `just-diff@3.0.2`. Let me know if it works for you!

I will dig into that clone blog when I get a chance, and try to answer your question!

**Comment by angus-c** [comment]
(Nice site btw!)

What did you use to compare performance of clone techniques?

**Comment by davidhq** [comment]
I measured in multiple ways and on multiple systems.

macOS -- real use case: cloning the state of an app:

1) function clone(obj) {
  return JSON.parse(JSON.stringify(obj));
}

```
Measured cloning state - 458 μs
Measured cloning state - 750 μs
Measured cloning state - 466 μs
Measured cloning state - 760 μs
Measured cloning state - 461 μs
Measured cloning state - 523 μs
Measured cloning state - 371 μs
Measured cloning state - 795 μs
Measured cloning state - 598 μs
Measured cloning state - 920 μs
Measured cloning state - 497 μs
Measured cloning state - 812 μs
Measured cloning state - 1.27 ms
Measured cloning state - 470 μs
Measured cloning state - 870 μs
Measured cloning state - 821 μs
Measured cloning state - 465 μs
Measured cloning state - 438 μs
Measured cloning state - 457 μs
Measured cloning state - 792 μs
Measured cloning state - 601 μs
Measured cloning state - 807 μs
Measured cloning state - 814 μs
Measured cloning state - 511 μs
Measured cloning state - 831 μs
Measured cloning state - 815 μs
Measured cloning state - 572 μs
Measured cloning state - 920 μs
Measured cloning state - 527 μs
Measured cloning state - 844 μs
Measured cloning state - 606 μs
Measured cloning state - 472 μs
Measured cloning state - 457 μs
Measured cloning state - 854 μs
Measured cloning state - 611 μs
Measured cloning state - 865 μs
Measured cloning state - 860 μs
Measured cloning state - 920 μs
Measured cloning state - 843 μs
Measured cloning state - 544 μs
Measured cloning state - 489 μs
Measured cloning state - 441 μs
Measured cloning state - 399 μs
Measured cloning state - 494 μs
Measured cloning state - 863 μs
Measured cloning state - 868 μs
Measured cloning state - 890 μs
Measured cloning state - 901 μs
Measured cloning state - 909 μs
Measured cloning state - 629 μs
Measured cloning state - 474 μs
```

2) const clone = require('./utilities/just/collection-clone')

```
Measured cloning state - 86 μs
Measured cloning state - 179 μs
Measured cloning state - 87 μs
Measured cloning state - 189 μs
Measured cloning state - 94 μs
Measured cloning state - 196 μs
Measured cloning state - 92 μs
Measured cloning state - 179 μs
Measured cloning state - 80 μs
Measured cloning state - 212 μs
Measured cloning state - 157 μs
Measured cloning state - 117 μs
Measured cloning state - 96 μs
Measured cloning state - 91 μs
Measured cloning state - 162 μs
Measured cloning state - 176 μs
Measured cloning state - 92 μs
Measured cloning state - 82 μs
Measured cloning state - 96 μs
Measured cloning state - 218 μs
Measured cloning state - 204 μs
Measured cloning state - 110 μs
Measured cloning state - 211 μs
Measured cloning state - 105 μs
Measured cloning state - 99 μs
Measured cloning state - 185 μs
Measured cloning state - 181 μs
Measured cloning state - 142 μs
Measured cloning state - 170 μs
Measured cloning state - 286 μs
Measured cloning state - 171 μs
Measured cloning state - 192 μs
Measured cloning state - 173 μs
Measured cloning state - 206 μs
Measured cloning state - 162 μs
Measured cloning state - 131 μs
Measured cloning state - 98 μs
Measured cloning state - 171 μs
Measured cloning state - 129 μs
Measured cloning state - 176 μs
Measured cloning state - 175 μs
Measured cloning state - 173 μs
Measured cloning state - 201 μs
Measured cloning state - 127 μs
Measured cloning state - 136 μs
Measured cloning state - 130 μs
Measured cloning state - 175 μs
Measured cloning state - 191 μs
Measured cloning state - 184 μs
Measured cloning state - 172 μs
Measured cloning state - 181 μs
Measured cloning state - 152 μs
```

```JavaScript
function measure(func, { desc = ' ', disable = false } = {}) {
  if (disable) {
    return func();
  }

  const start = stopwatch.start();
  const result = func();
  const duration = stopwatch.stop(start);
  const line = colors.gray(`Measured ${colors.cyan(desc)} -`);
  console.log(`${line} ${colors.green(duration)}`);
  
  return result;
}
```

stopwatch.js

```JavaScipt
const stopwatch = require('pretty-hrtime');

function start() {
  return process.hrtime();
}

function stop(start) {
  const end = process.hrtime(start);
  return stopwatch(end);
}

module.exports = { start, stop };
```

RaspberryPi 3B+

JSON.stringify/parse
```
Measured cloning state - 2.13 ms
Measured cloning state - 1.87 ms
Measured cloning state - 1.87 ms
Measured cloning state - 1.89 ms
Measured cloning state - 1.86 ms
Measured cloning state - 1.94 ms
Measured cloning state - 14 ms
Measured cloning state - 2.9 ms
Measured cloning state - 2.61 ms
Measured cloning state - 2.94 ms
Measured cloning state - 4.41 ms
Measured cloning state - 4.44 ms
Measured cloning state - 4.56 ms
Measured cloning state - 4.65 ms
Measured cloning state - 4.68 ms
Measured cloning state - 4.71 ms
```

just-clone

```
Measured cloning state - 1.1 ms
Measured cloning state - 2.82 ms
Measured cloning state - 428 μs
Measured cloning state - 405 μs
Measured cloning state - 427 μs
Measured cloning state - 824 μs
Measured cloning state - 848 μs
Measured cloning state - 596 μs
Measured cloning state - 526 μs
Measured cloning state - 568 μs
Measured cloning state - 944 μs
Measured cloning state - 964 μs
Measured cloning state - 994 μs
Measured cloning state - 1.02 ms
Measured cloning state - 1.03 ms
Measured cloning state - 1.09 ms
```

With this simple script: 
https://gist.github.com/davidhq/e56be8bbeb03a8ab44038115feb3fbb3

I used this `program.json`:
https://gist.github.com/davidhq/c9f3128734b9c604f88b26b0ef9effd5

 I got (on MacBook PRO 2015):

1) JSON.stringify/parse
around 110ms +- 2 on my mac for this loop

2) structuredClone
around 120ms

3) just-clone
~25ms +- 1

4) fast-clone was also not "very fast", forgot the measure and won't test again now

**Comment by angus-c** [comment]
Hmm interesting. I wonder if `just-clone` doesn't cover the same feature set as other techniques. (I know for one thing it won't detect circular references). However it does clone non-serializable values (unlike JSON/parse/stringify)  

In any case those are impressive numbers if you want basic cloning functionality.

**Comment by davidhq** [comment]
Your code for cloning is so simple... It's strange that I had to stumble into this by coincidence and it does seem to be the best way to clone an object for most purposes... and it makes a big difference for this particular project... We may learn what's the catch some day :) or it remains a mystery and it's ok as long as it works (fast).

**Comment by davidhq** [comment]
Hey Angus!! This thread came handy! I hope you don't mind "using it a bit"... but some idiots really need verbatim explaining, even over-doing it sometimes! :) I mean the line I mean the line "people from Twitter and Uber"... https://www.reddit.com/r/psytrance/comments/ec9oz8/dmtplayer/

TO THE POSITIVITY and SHAVING OFF MILLISECONDS :)

**Comment by angus-c** [comment]
Ha no problem!
