### ISSUE TITLE
just-shuffle returns a subset of permutations

### ISSUE THREAD

**Issue by chocolateboy** [angus-c/just#172]
### System

- **just-shuffle**: 2.1.0
- **Node.js**: v13.8.0
- **OS**: Linux (Arch)

### Test

```typescript
const justShuffle = require('just-shuffle')
const lodashShuffle = require('lodash.shuffle')

const just = {}, lodash = {}

function store (target, shuffled) {
    const json = JSON.stringify(shuffled)
    target[json] = (target[json] || 0) + 1
}

for (let i = 1; i <= 1_000_000; ++i) {
    store(lodash, lodashShuffle([1, 2]))
    store(just, justShuffle([1, 2]))
}

console.log('lodash:', lodash)
console.log('just:', just)
```

#### lodash.shuffle

```javascript
{ '[2,1]': 499792, '[1,2]': 500208 }
```

#### just-shuffle

```javascript
{ '[2,1]': 1000000 }
```

**Comment by chocolateboy** [comment]
Results for `[1, 2, 3]`:

### lodash.shuffle

```javascript
{
  '[1,2,3]': 166776,
  '[2,1,3]': 167052,
  '[3,2,1]': 165762,
  '[3,1,2]': 166995,
  '[2,3,1]': 166520,
  '[1,3,2]': 166895
}
```

### just-shuffle

```javascript
{ '[3,1,2]': 500233, '[2,3,1]': 499767 }
```

**Comment by angus-c** [comment]
This was by design—the util only returns arrays where none of the elements are in their original position. Leaving open while I decide whether to make it compatible with lodash

**Comment by angus-c** [comment]
I think the best way to go is for the function to take a `fullShuffleOnly` argument (probably not the best name), which defaults to `false`. This will require a breaking version obviously

**Comment by chocolateboy** [comment]
> the util only returns arrays where none of the elements are in their original position

Is there a use case for this behavior? Do you use use it somewhere? AFAICT, no other shuffles behave in this way, and I'd be very surprised if anyone who uses this library expects this behavior by default, e.g.:

- [JohnForster/pandemic-ts](https://github.com/JohnForster/pandemic-ts/blob/54c7a307ee5c4c328d0f0b3fd314fad74f62a731/src/app/helpers/createInitialGameState.ts#L3)
- [puckey/dance-tonite](https://github.com/puckey/dance-tonite/blob/966f3742f6bae1602ceea1e6c162f5c8401d33ac/src/components/ThanksTimeline/index.js#L16
)
- [remarcable/ClickTheNumber](https://github.com/remarcable/ClickTheNumber/blob/575b7213ed59145ae8bc5df493e612dc082db6de/src/lib/RandomRange.js#L1)

At the very least, I think it would be a good idea to prominently document this behavior (it's not mentioned at all currently). Alternatively, maybe link to one of the alternatives for anyone expecting the standard behavior? (In the end I went with [array-shuffle](https://www.npmjs.com/package/array-shuffle).)

**Comment by angus-c** [comment]
Yeah you make a good point.
Going to cut a major version with random shuffle as default, and `allElementsMustMove` as an option.

**Comment by angus-c** [comment]
created just-shuffle@3.0.1
```js
justShuffle([1,2]); // could be [1,2] or [2,1]
justShuffle([1,2], {shuffleAll: true}); // always [2,1]
```
