### ISSUE TITLE
[just-extend]: work with Object.create(null)

### ISSUE THREAD

**Issue by foodforarabbit** [angus-c/just#190]
Recently I tried using this on `ctx` in fusion/koa and ran into these two issues:

1)  `Object.create(null)` in events library: https://github.com/Gozala/events/blob/master/events.js#L92

This will throw the following error when using Object.prototype functions on it:
```
TypeError: Cannot convert object to primitive value
```
2) Circular references

**Comment by angus-c** [comment]
As per #191, trimming this issue to just include safe hasOwnProperty

**Comment by angus-c** [comment]
Fixed by #198
