### ISSUE TITLE
safe-set should have the possibility to set values if object/attributes does not exist

### ISSUE THREAD

**Issue by a-tonchev** [angus-c/just#204]
To be equal of the lodash functionality the example

// don't clobber existing
const obj4 = {a: {aa: {aaa: 2}}};
set(obj4, 'a.aa', {bbb: 7}); // false

Should actually add attribute bbb to the aa key

https://lodash.com/docs/4.17.15#set

Best regards

**Comment by angus-c** [comment]
I believe this works as stated in 2.1.0

Paste this code [here](https://anguscroll.com/just/just-safe-set) to verify

```
const set = require('just-safe-set');

const obj4 = {a: {aa: {aaa: 2}}};
set(obj4, 'a.aa', {bbb: 7});
obj4;
```
