### ISSUE TITLE
Deep Merging

### ISSUE THREAD

**Issue by smlmrkhlms** [angus-c/just#216]
I am currently looking for an alternative to `lodash` and I stumbled across your awesome project. One of our primary use cases for `lodash` is their `lodash.merge` utility, which merges objects deeply. I was wondering if there a way to do that with one of this library's utilities. If not, would you see value in adding this capability to the `just-merge` utility? Thank you!

**Comment by angus-c** [comment]
Hi Mark, [just-clone](https://anguscroll.com/just/just-clone) is what you want!

**Comment by smlmrkhlms** [comment]
Thanks @angus-c!
