### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by hagaiwech** [angus-c/just#234]
Hi team,

I've tried to contact you in mail, but there was no response, can you please contact me ?

hagai.wechsler@whitesourcesoftware.com

Thanks,
Hagai

**Comment by angus-c** [comment]
Hi Hagai,

Due to volume, an out of an abundance of caution I don't generally reply to emails from unknown recipients. Feel free to leave an issue here.

**Comment by hagaiwech** [comment]
Hi,

I'm approaching you regarding a security issue.
We don't usually post security issues publicly on Github, but if you want we can post here our security report with our findings.

What do you prefer?

Thanks,
Hagai

**Comment by angus-c** [comment]
Hi, I'm fine with you posting it as an issue
