### ISSUE TITLE
just-range crashes devtools

### ISSUE THREAD

**Issue by dfcreative** [angus-c/just#25]
Hi @angus-c!
Awesome collection, I use it here and there.
One gotcha:
```js
let range = require('just-range');
range(5.4, 11.200000000000001, 0.2)
```
Crashes devtools.

**Comment by dfcreative** [comment]
A question: why [here](https://github.com/angus-c/just/blob/master/packages/array-range/index.js#L20) we have a strong equal condition, not the `<=`?

**Comment by dawsonbotsford** [comment]
I helped build this one. The original intent was solely focused on integers. I can see why you'd want to have a range that doesn't involve just integers though. Would you like to do the honors of the PR @dfcreative? If not, I can.

**Comment by dfcreative** [comment]
I came up with that workaround:
```js

function range(start, stop, step) {
  if (stop == null) {
    stop = start || 0;
    start = 0;
  }
  if (step == null) {
    step = stop > start ? 1 : -1;
  }
  var toReturn = [];
  var increasing = start < stop; //← here’s the change
  for (; increasing ? start < stop : start > stop; start += step) {
    toReturn.push(start);
  }
  return toReturn;
}
```
Not convinced it is good though, if you know better solution @dawsonbotsford, then let us better have your PR :)

**Comment by dawsonbotsford** [comment]
That looks nice instead, my PR was such a split-second response that I missed all of the negative test cases. What do you think of the approach above @angus-c?

Ignore my PR for now

**Comment by angus-c** [comment]
This looks nice. Thanks both of you. Will need a new test I guess.

**Comment by dawsonbotsford** [comment]
My PR is updated with @dfcreative's loop method and some new tests (that previously failed).

**Comment by angus-c** [comment]
fixed by #26

**Comment by dfcreative** [comment]
Awesome!
@angus-c could you please bump npm version? Thanks!

**Comment by angus-c** [comment]
yeah - sorry forgot that. Will do tonight.

**Comment by dfcreative** [comment]
@angus-c sorry to bug, but is there any progress on that?

**Comment by angus-c** [comment]
@dfcreative done! Sorry for the delay.
