### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by shellscape** [angus-c/just#280]
Hey there. I ran across your `just-throttle` package today. I like what you've done with all of these zero dep packages, but the documentation is pretty poor for a consumer not already familiar with the code. When writing documentation, it's important to note that the consumer of those docs will likely never source dive your package, so it needs to be spelled out clearly what options do what, and how they work together. Without source diving, I have no idea what `leading` and `trailing` mean in this context.

**Comment by angus-c** [comment]
Yeah good point. Will address this

**Comment by angus-c** [comment]
Done
