### ISSUE TITLE
collection-diff question

### ISSUE THREAD

**Issue by pete-hotchkiss** [angus-c/just#291]
This is a question more than an issue, but I've been digging around the library in recent days; and I've a question around a specific part of the `diff` method.

at line 119 you have an `if` block...

```
if (
  !Object.keys(obj1AtKey).length &&
  !Object.keys(obj2AtKey).length &&
  String(obj1AtKey) != String(obj2AtKey)
)
``` 

I'm trying to get a handle on what sort of change in two objects might trigger the code to step into this statement.

Can you give an example at all ?

**Comment by angus-c** [comment]
It's part of the strategy to determine whether the current property in each object is iterable (i.e. do both have child properties). If both are iterable we do a recursive call, if not we push a diff to our array of diffs.

The previous code block checked if either property was  a primitive
```
        if (
          Object(obj1AtKey) !== obj1AtKey ||
          Object(obj2AtKey) !== obj2AtKey
        ) {
```

This code block completes the check by looking for non-primitive properties without children. These include functions, dates and regexes (without additional properties) and primitives cast to objects (e.g. `String('hi')`).

Hope this helps!

**Comment by pete-hotchkiss** [comment]
this definitely helps - and makes sense now. Thanks for taking the time to respond
