### ISSUE TITLE
extend not extending arrays

### ISSUE THREAD

**Issue by muuki88** [angus-c/just#299]
Hi,

Thanks for this library of small utility functions :heart: 

I'm trying to use [just-extend](https://github.com/angus-c/just/blob/master/packages/object-extend/index.js), but this method does not extend/merge arrays. Is this intended or a bug?

cheers,
Muki

**Comment by angus-c** [comment]
Thanks for the kind words Muki!

`just-extend` is designed only for non-array objects.
Does `just-union` do what you want? ([example](https://anguscroll.com/just/just-union))

**Comment by muuki88** [comment]
Thanks for your feedback :hugs: 

It would if it was a a toplevel array. In my case objects have nested arrays.

```javascript
const team1 = { name: 'team1', players: [ 'A', 'B' ], someOtherProps : { } };
const team2 = { name: 'team2', players: [ 'B', 'C' ], moreProps : { } };
```

In the spirit of this library there would probably need to be a third function `just-extend-or-merge` :grin:

**Comment by angus-c** [comment]
Haha, but yeah there does seem to be room for a new utility to do this
