### ISSUE TITLE
Bundling

### ISSUE THREAD

**Issue by sir-castiq** [angus-c/just#3]
Hey. Newbie here. would it be possible to include a way of bundling only packages I need together instead of npm installing them on a one by one basis. If this goes against what you're trying to do i'd appreciate if you could explain. thanks.

**Comment by hemantjadon** [comment]
Really it will be great to have such bundled feature, Can I try to submit a PR regarding this.

**Comment by angus-c** [comment]
What sort of bundling API did you have in mind?

You can install several packages at once with

```
npm install extend compare --save
```

**Comment by sir-castiq** [comment]
That works for me. Thanks for taking the time to answer. I was thinking something like a config file with all the packages specified but yours is faster and better.
