### ISSUE TITLE
safe-set clobbers existing sibling values

### ISSUE THREAD

**Issue by tmalaher** [angus-c/just#301]
This code:

```
const set = require('just-safe-set');

const obj4 = {a: {aa: {aaa: 2}}};
set(obj4, 'a.aa', {bbb: 7});
obj4;
```

Returns `true` from the set() call, and the resulting `obj4` is `{a: {aa: {bbb: 7}}}` not `{a: {aa: {aaa: 2, bbb: 7}}}` as expected.

_Originally posted by @angus-c in https://github.com/angus-c/just/issues/204#issuecomment-734997550_

**Comment by angus-c** [comment]
As that original issue says, It should add, not clobber.
This is the way lodash does it too

lodash
```
const obj4 = {a: {aa: {aaa: 2}}};
_.set(obj4, 'a.aa', {bbb: 7}); // {a: {aa: {bbb: 2}}}
```

just
```
const set = require('just-safe-set');

const obj4 = {a: {aa: {aaa: 2}}};
set(obj4, 'a.aa', {bbb: 7}); // {a: {aa: {bbb: 2}}}
```
