### ISSUE TITLE
List of modules without TS definitions

### ISSUE THREAD

**Issue by PuruVJ** [angus-c/just#313]
We're in the process of adding TypeScript definitions and tests to every Just utility. You're welcome to help us get there! [Here's](https://github.com/angus-c/just/pull/247/files) an example PR.

You can verify new TypeScript definitions by running `yarn test-types` (This also gets run as part of the `yarn test` script)

Here's a list of all the packages without TS definitions yet. Any contributors wanting to contribute TypeScript here could decide from this

# Collections

- [x] just-diff-apply
- [x] just-compare
- [x] just-pluck-it
- [x] just-flush

# Objects

- [x] just-entries
- [x] just-map-object
- [x] just-map-keys
- [x] just-reduce-object
- [x] just-is-primitive

# Functions

- [x] just-compose
- [x] just-demethodize
- [x] just-flip
- [x] just-partial-it

**Comment by angus-c** [comment]
Updated with to reflect new type additions. 22 left now.

**Comment by PuruVJ** [comment]
Got a question about Cartesian Product: Does it really have d.ts now? I updated my deps and VSCode still can't find it's typings 

![image](https://user-images.githubusercontent.com/47742487/139567259-90666aef-7622-4f00-9ac1-ce930b6cc52f.png)

**Comment by angus-c** [comment]
Should be published now

**Comment by maxsynnott** [comment]
just-truncate PR #353

**Comment by angus-c** [comment]
Thanks Max. All landed except #356 (see comment)

**Comment by maxsynnott** [comment]
> Thanks Max. All landed except #356 (see comment)

Answered #356

**Comment by PuruVJ** [comment]
Now the hardest functions left to add the TS typings for 🥲

**Comment by Aryaman1706** [comment]
Added typings for `just-map-keys`.
Kindly have a look:- #368

**Comment by maxsynnott** [comment]
just-is-primitive #391

**Comment by maxsynnott** [comment]
just-map-object should be checked off

**Comment by PuruVJ** [comment]
Done @maxsynnott

**Comment by Aryaman1706** [comment]
Added types for just-flip
Kindly have a look #406

**Comment by Aryaman1706** [comment]
Added types for just-flush
Kindly have a look #408

**Comment by eddie-atkinson** [comment]
Added just-diff-apply #409

**Comment by seiyab** [comment]
Added just-pluck-it https://github.com/angus-c/just/pull/389

**Comment by PuruVJ** [comment]
@angus-c lots of great stuff happening here 🔥

**Comment by PuruVJ** [comment]
Only 6 packages left! 🔥

**Comment by angus-c** [comment]
One left! Thanks to @Masa-Shin

**Comment by breggle** [comment]
Added type definitions for function-curry #446 
Well, it is just okay to call the curried function without any arguments. Not sure this is wanted? That PR do not prevent this, but it can with a litter modification.

**Comment by PuruVJ** [comment]
Only one package left for typescript 🥳

**Comment by TClark1011** [comment]
I've opened a PR with typings for the last package #469

**Comment by angus-c** [comment]
And we're done! Many thanks to everyone who helped with this. Great job!
