### ISSUE TITLE
Conflict between compose comments and README

### ISSUE THREAD

**Issue by jfsiii** [angus-c/just#329]
I was curious if compose worked right-to-left or vice-versa. The code comments and README disagree

https://github.com/angus-c/just/blob/055f8730d82a74a98d0f45ee619f6f97f87d3d8f/packages/function-compose/index.js#L4-L6

https://github.com/angus-c/just/blob/055f8730d82a74a98d0f45ee619f6f97f87d3d8f/packages/function-compose/README.md#L11-L13

Which is correct? Are there tests for this function? Any test to ensure examples are correct?

Thanks for the help and the library!

**Comment by brandonryan** [comment]
Just want to use this issue for a discussion. I think it might be a good idea to generate docs based on the `@example` jsdoc (as well as the description from there). Probably just strip out all the usage comments in the files. I'm pretty sure there are some libraries around that will do that pretty easily and you just just stitch them all together into the readme.

**Comment by angus-c** [comment]
Hi @jfsiii, it's left to right. I will fix the comments.
The easiest way to test is via the REPL: https://anguscroll.com/just/just-compose
The tests are here: https://github.com/angus-c/just/blob/master/test/function-compose/index.js

**Comment by angus-c** [comment]
@brandonryan yeah when I get to it :)
