### ISSUE TITLE
Wrong example of just-safe-get

### ISSUE THREAD

**Issue by hmmhmmhm** [angus-c/just#331]
<img width="417" alt="스크린샷 2021-11-01 오전 1 40 39" src="https://user-images.githubusercontent.com/38493722/139593630-1520b13c-9830-4e07-ad78-2a5da6aa889d.png">

I think people won't be confused only when they deliver examples of successful operation.
It would be nice if the example was revised as below.
```js
const get = require('just-safe-get');

const obj = {a: {aa: {aaa: 2}}, b: 4};
get(obj, 'a.aa.aaa');
```

**Comment by angus-c** [comment]
I see your point but on balance I think the most useful feature of the utility is it doesn't thrown an exception if a part of the property chain is missing. So I think I'll stick with what I have.
Also folks can click the API link to see more examples
https://github.com/angus-c/just#just-safe-get
