### ISSUE TITLE
NextJS incompatibility

### ISSUE THREAD

**Issue by rqbazan** [angus-c/just#332]
Hey @angus-c 👋

Seems like [the latest version of all the packages](https://github.com/angus-c/just/pull/315) has introduced an incompatibility with NextJS apps.

### Reproduce

1. Clone https://github.com/rqbazan/just-and-nextjs-esm-issue
2. Install all dependencies with `yarn`
3. Run the build process: `yarn build` ❌
4. Profit!

```bash
./node_modules/just-map-values/index.esm.js
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (22:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
|
> export { objectMapValues as default };
|
```

### Possible solution

- Change `"commonjs"` to `"module"` in package.json

After the change to `"type": "module"` you can run `yarn build` ✅:

```
rm -rf .next && yarn build
```

**Comment by nosovk** [comment]
yep, svelte-kit builds also broke on latest update (and they are "module"  from start)

broken build one:
https://github.com/NodeArt/nodeartio/pull/454

accidentally merged broken version
https://github.com/MailCheck-co/mailcheck.site/pull/601
and reverting it restored build 
https://github.com/MailCheck-co/mailcheck.site/commit/c8af869dccb6dd97a17fe9d777254d618bf3a573

it seems that ESM build isn't correct for now (or it's declaration in package.json)

**Comment by nosovk** [comment]
https://github.com/angus-c/just/pull/328
that one also should be merged (I was wrong, real problem fixed in that PR) by @PuruVJ

**Comment by angus-c** [comment]
#328 merged.
Considering other issue now (cc @raulfdm)

**Comment by angus-c** [comment]
Should be fixed now https://github.com/angus-c/just/pull/334

**Comment by raulfdm** [comment]
Sorry my absence, I had to stay offline yesterday the whole day...

Curious to understand why nextjs was picking up ESM if the main type was specified to to commonjs. 

Anyhow, I'm glad it's fixed. I should've tested in all biggest frameworks (nuxt, next, vite, angular, node, etc) to ensure it's all working perfectly everything. My bad

**Comment by angus-c** [comment]
> yep, svelte-kit builds also broke on latest update (and they are "module" from start)

Hi @nosovk can you check with latest major build? It now uses .mjs suffix for esm module  which should be more universally recognized

**Comment by PuruVJ** [comment]
@angus-c I checked just-shuffle, and it is working in sveltekit, so assumption is that all of em are working. Even I had the same problem with submodules, and renaming ESM outputs to .mjs helped, so all of just packages should also work

**Comment by angus-c** [comment]
Cool, thanks for confirming @PuruVJ. @nosovk said it also now works for him.
