### ISSUE TITLE
add these utils

### ISSUE THREAD

**Issue by angus-c** [angus-c/just#36]
just-zip

**Comment by suhasdeshpande** [comment]
Is this something I can take a stab at?

**Comment by angus-c** [comment]
You can have a stab at [just-zip](http://colin-dumitru.github.io/functional-programming/javascript/tutorial/2014/12/28/functional_operations_in_es6.html#zip) if you like. I'll warn you I'm a difficult repo owner though — I usually asks for loads of edits to PRs :)

**Comment by angus-c** [comment]
Not using map though—no higher order functions

**Comment by kamilogorek** [comment]
Spread and no error handling version:

```js
function zip (...args) { 
  var result = [];
  var inputLength = args.length;
  var maxLen = 0;

  for (var i = 0; i < inputLength; i++) {
    var arrLen = args[i].length;

    if (arrLen > maxLen) {
      maxLen = arrLen;   
    }                    
  }                      
                         
  for (var i = 0; i < maxLen; i++) {
    var group = [];
                         
    for (var j = 0; j < inputLength; j++) {
      group[j] = args[j][i]                                                                                                                                                   
    }

    result[i] = group
  }                      
                         
  return result          
}    
```

ES5 version:

```js
function zip () {
  var args = Array.prototype.slice.call(arguments)
  var result = []
  var inputLength = args.length;
  var maxLen = 0;
 
  for (var i = 0; i < inputLength; i++) {
    // or if (Object.prototype.toString.call([]) !== '[object Array]') if you don't want to use Array.isArray
    if (!Array.isArray(args[i])) {
      throw new TypeError('zip function can only take arrays as an arguments')
    }
 
    var arrLen = args[i].length
    if (arrLen > maxLen) {
      maxLen = arrLen;
    }
  }
 
  for (var i = 0; i < maxLen; i++) {
    // skipping `group` var from previous example
    result[i] = []
    for (var j = 0; j < inputLength; j++) {
      result[i][j] = args[j][i]
    }
  }
 
  return result
}
```

**Comment by angus-c** [comment]
https://github.com/angus-c/just/pull/41

**Comment by abozhilov** [comment]
Am I missing something or this is a `longZip`? For example Python's `zip` the returned list length is equal to  the length of the shortest list passed as argument.

**Comment by abozhilov** [comment]
How about: 

```
    var maxLen = args.reduce(function (currMax, arr) {
        if (arr.length > currMax) {
            return arr.length;
        }
        return currMax;
    }, 0);
```

?

**Comment by abozhilov** [comment]
IMHO it should work with any Array like objects. There is no need of checking `Array.isArray(args[i])`

**Comment by kamilogorek** [comment]
@abozhilov this implementation is in line with `zip` definition from wiki – https://en.wikipedia.org/wiki/Convolution_(computer_science)#Definition

You are totally right that Python, Haskell and most of the languages are truncating an input, however, Underscore and LoDash are using the longest input, and I believe that keeping it the same here is a better option.

@angus-c didn't want to use higher-order functions, therefore I skipped `reduce` :)

If you won't check for `Array.isArray(args[i])`, then `args[i].length` will throw a `TypeError` if given `undefined` value.
