### ISSUE TITLE
what does functions-partial do?

### ISSUE THREAD

**Issue by PuruVJ** [angus-c/just#360]
Hi, the docs about functions-partial are not clear. What does this function do?

**Comment by angus-c** [comment]
Yeah a one sentence description in the README would be useful, though in a way this one is best explained by example. Also the README was wrong 😱 (fixed now)

The `partial` function wraps an existing function (first argument) and the remaining arguments are pre-passed as arguments to the returned function. If any argument in `partial` is undefined it is expected to be supplied at runtime.

So in this example, `1/3` will always be passed as the second argument to the returned function. The first argument will be passed at runtime.
`const cubedRoot = partial(Math.pow, _, 1/3);`

So `cubedRoot(4)` is the same as `Math.pow(4, 1/3)`

**Comment by PuruVJ** [comment]
ok, and what's the _ here? 🤔

**Comment by angus-c** [comment]
Whoops should have been `undefined`. Edited my comment
