### ISSUE TITLE
Many packages are lacking descriptions

### ISSUE THREAD

**Issue by maxsynnott** [angus-c/just#361]
Many packages are lacking descriptions and instead just have examples. This forces the user to interpret the functions purpose themselves which can lead to misunderstandings.

I suggest each package should have a minimum of a one sentence description in its README.md
Could also extend this to use jsdoc to include descriptions in the editor

I could contribute some descriptions

Thoughts? @angus-c

**Comment by PuruVJ** [comment]
yeah, I had this issue too. #360

**Comment by angus-c** [comment]
Yeah a one sentence description in the README would be helpful. There is a one sentence description in the package.json (though some leave a bit to be desired).

I'd prefer just a manual README update for now. (It's a pain because there is the local and global README for ever package. But I'm trying to keep build steps to a minimum).

**Comment by maxsynnott** [comment]
There's currently three places the descriptions exist per package. Global README, local README and package.json.

Can I please ask why you want to keep build steps to a minimum? To avoid complexity?

**Comment by angus-c** [comment]
Of course I'm not in favor of drudge work for drudge work's sake, so (e.g.) a script to generate the global README content from local READMEs would make sense. But in general I'm ok with Just's low tech-ness (and that's also kind of its point) and am wary of adding build steps with limited maintenance value. 

BTW there's no overlap between package.json description and the README content

**Comment by maxsynnott** [comment]
I'm going to work on generating the global README content from the local READMEs as many of them are currently misaligned which I think should be fixed.

I'll keep it as basic as possible to avoid potential maintenance

**Comment by angus-c** [comment]
That's great. Thanks @maxsynnott

**Comment by angus-c** [comment]
@maxsynnott We should standardize on formats.
Suggestion (let me know what you think): 

local README (some of these had `npm install <name>` directives but I think we should drop these from local)
```
## just-<name>

Part of a [library](http://anguscroll.com/just) of zero-dependency npm modules that do just do one thing.  
Guilt-free utilities for every occasion.

[Try it now](http://anguscroll.com/just/just-<name>)

<one or two sentence description>

\```js
<examples>
\```
```

global README (since this is probably the first place folks will look for docs I think we should keep `npm install <name>` directive and add one for yarn too)
```
### [just-<name>](https://www.npmjs.com/package/just-<name>)

:icecream:[`Try It`](https://anguscroll.com/just/just-<name>)

`npm install <name>`
`yarn add <name>`

<one or two sentence description>

\```js
<examples>
\```
```

**Comment by maxsynnott** [comment]
I agree this would be a good idea. I made a couple adjustments to the above to keep them more aligned and also added a source code link. 

Let me know what you think.

LOCAL:

```
## just-cartesian-product

Part of a [library](http://anguscroll.com/just) of zero-dependency npm modules that do just do one thing.  
Guilt-free utilities for every occasion.

[`🍦 Try it`](https://anguscroll.com/just/just-<name>)


```shell
npm install <name>
```

```shell
yarn add <name>
```

<description>

```js
<examples>
```
```

GLOBAL:

```
### [just-cartesian-product](https://www.npmjs.com/package/just-<name>)
[source](https://github.com/angus-c/just/packages/<packageDir>/index.js)

[`🍦 Try it`](https://anguscroll.com/just/just-<name>)


```shell
npm install <name>
```

```shell
yarn add <name>
```

<description>

```js
<examples>
```
```

**Comment by angus-c** [comment]
Yeah this looks good. Maybe remove the space between the two shell snippets? (just want to keep it compact—although maybe line breaks are automatically added after `shell` anyway, idk)
