### ISSUE TITLE
No changelog present?

### ISSUE THREAD

**Issue by DannyvanHolten** [angus-c/just#366]
Hey hey, I'm getting a message from Dependabot this needs to be updated to a new major version, 3.1.1 > 4.0.0. Which means probably something is breaking according to semver. But I cannot find any changelog whatsoever. So I have no clue what changed. 

Can somebody help me out?

**Comment by angus-c** [comment]
Hey @DannyvanHolten. 
Yeah I should probably add change logs. The change is the exported esm module now uses .mjs suffix. If you are using the original common js module then the change is non-breaking

**Comment by DannyvanHolten** [comment]
Thanx for the answer for now :D 

But yeah. Changelog would be great!

**Comment by angus-c** [comment]
With the help of  [changesets](https://github.com/changesets/changesets) I'm now adding a changelog for significant changes
