### ISSUE TITLE
why is the `test` module a production dependency?

### ISSUE THREAD

**Issue by atuttle** [angus-c/just#378]
Why isn't it a devDependency? If there's a considered reason with a chosen trade-off, that would be reasonable... but from an outsider perspective it seems like what was intended to be a 0-dependency library now depends on `test` which depends on `ansi-font`.

**Comment by angus-c** [comment]
Thanks, I moved it to a dependency. Just FYI though, zero dependencies refers to the individual packages, not to the monorepo.
