### ISSUE TITLE
Proposal for a new array function reverseEach to iterate array in reverse order

### ISSUE THREAD

**Issue by themudassarhassan** [angus-c/just#398]
A new array function with name `reverseEach` can be added to achieve array traversal in reverse order, just like we have `forEach` for simple traversal.

**Comment by themudassarhassan** [comment]
given an array `const arr = [1, 2, 3, 4];`
the implementation of the function might look something like
```
function reverseEach(arr, cb) {
  let lastIndex = arr.length - 1;
  while (lastIndex >= 0) {
    cb(arr[lastIndex], lastIndex--);
  }
}
```
and use it like 
```
reverseEach(arr, (value, index) => {
  console.log(value, index);
});
```
Please let me know what you guys think, so I can create a PR for that. thanks!

**Comment by angus-c** [comment]
Thanks for your proposal @themudassarhassan !
Though it might sometimes be useful, folks could also do `arr.slice().reverse().forEach` for smaller arrays and use the native `reduceRight` for larger ones.

Interested to get other opinions @maxsynnott @PuruVJ @brandonryan

**Comment by maxsynnott** [comment]
Hmm the current best way of doing this is:

```
for (let i = arr.length - 1; i >= 0; i--) {
    const value = arr[i]
    ...
} 
```
or
```
arr.reduceRight((_, value) => ..., null)
```

While I agree that a ```reverseEach``` function would be more convenient than the above options, I personally think the need for it is too uncommon to warrant it's own function.

How often and why do you have an array sorted in the exact reverse order that you need to iterate through it? Maybe I'm missing some good common use cases but can't really think of them.

**Comment by angus-c** [comment]
Yeah inclined to agree

**Comment by angus-c** [comment]
Hey Mudassar, really appreciate the suggestion but I'm going to close this issue because I want to limit the Just suite to those utilities with definite value.
