### ISSUE TITLE
npm @just organization

### ISSUE THREAD

**Issue by brandonryan** [angus-c/just#422]
Since orgs are free now with unlimited packages, you might consider grouping all packages under the `@just/` organization while its available. This would help people find your other packages and help with name conflicts. I would be willing to help with this if wanted.

**Comment by angus-c** [comment]
Thanks for the offer @brandonryan . How does backwards compatibility work here? Will links and imports redirect?

**Comment by brandonryan** [comment]
Basically, you would publish to the new package and then deprecate the old one. People who install the old one will get a deprecation message.
https://docs.npmjs.com/cli/v8/commands/npm-deprecate

**Comment by angus-c** [comment]
Decided against this
