### ISSUE TITLE
Could not find a declaration file for module 'just-omit' with Typescript 4.7

### ISSUE THREAD

**Issue by jscheid** [angus-c/just#428]
This might not be a problem because Typescript 4.7 isn't an official release (yet), but I'm getting this error message:

```
src/file.ts(6,18): error TS7016: Could not find a declaration file for module 'just-omit'. '/path/to/node_modules/just-omit/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/just-omit` if it exists or add a new declaration (.d.ts) file containing `declare module 'just-omit';`
```

All the many other TS packages I'm using seem to work fine, that's why I thought I'd raise it.

My `tsconfig.json` and `yarn.lock` are here: https://gist.github.com/jscheid/afa11309bf44789ac75ffa51163e061f
Let me know if you need anything else from me.

**Comment by angus-c** [comment]
See #429

**Comment by angus-c** [comment]
See https://github.com/angus-c/just/issues/468
