### ISSUE TITLE
just-omit does not omit deep value

### ISSUE THREAD

**Issue by lsbyerley** [angus-c/just#433]
Consider the following example, `__typname` is not removed from the nested extract object.

```javascript
omit(input, ['__typename'])

const input = {
  created: 'today',
  extract: {
    __typename: 'asdf',
  },
  __typename: 'asdf',
}

const expectedOutput = {
  created: 'today',
  extract: {},
};

const receivedOutput = {
  created: 'today',
  extract: {
    __typename: 'asdf',
  },
}
```

**Comment by Nikaple** [comment]
I think this is the intended behavior, see [lodash docs](https://lodash.com/docs/4.17.15#omit)

**Comment by lsbyerley** [comment]
I don't think that is the case. I am switching out lodash omit for just-omit and the lodash omit performs a deep omit on the object whereas just-omit does not.

**Comment by angus-c** [comment]
I don't see that behavior in lodash

```
const input = {
  created: 'today',
  extract: {
    __typename: 'asdf',
  },
  __typename: 'asdf',
}

_.omit(input, ['extract.__typename']); // no properties removed 
```
