### ISSUE TITLE
TypeScript | just-omit doesn't show error when passing unknown object properties

### ISSUE THREAD

**Issue by ilearnio** [angus-c/just#445]
"just-omit" is not showing errors when passing object properties that don't exist in an object. It should be an easy fix:

In https://github.com/angus-c/just/blob/master/packages/object-omit/index.d.ts just need to replace `Key extends string` with `Key extends keyof Obj`. Sorry for not creating a PR, I just think there should be more similar packages that need to be updated in similar way.

![image](https://user-images.githubusercontent.com/14331216/163569324-2054ceb9-87aa-46d6-991f-1251c4b49d96.png)

**Comment by angus-c** [comment]
Thanks @ilearnio. Although the code change looks robust, it goes against the design of the utility. It was my intention that it should silently ignore any remove property that does not exist in the object. Both object properties and remove properties can be dynamic and it can be inconvenient to be bound by this kind of rule (e.g. what if two async transactions are trying to omit the same property in quick succession).

 I even wrote a test to explicitly allow it https://github.com/angus-c/just/blob/master/test/object-omit/index.js#L35
