### ISSUE TITLE
Is `just-merge` supposedly the same as `lodash/extend`?

### ISSUE THREAD

**Issue by ardok** [angus-c/just#455]
It looks like it's not?
<img width="440" alt="image" src="https://user-images.githubusercontent.com/1380581/169352411-b68f6205-8256-4dc2-aafe-19dcd4655859.png">
I expect `b` to have `one` and `two`.

-----

Same with `just-extend`, it doesn't seem to do "deep merge".

**Comment by ardok** [comment]
This is `lodash/merge`:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/1380581/169352768-3f2c0488-b186-4020-8e76-282844d9600c.png">

**Comment by angus-c** [comment]
just-merge is shallow copy
just-merge is optional deep copy (pass true as first argument)
```
let obj = {a: 3, b: {one: 'one'}};
merge(true, obj, {a: 4, b: {two: 'two'}}); // {a: 4, b: {one: "one", two: "two"}}
```
