### ISSUE TITLE
Switch to namespaced modules.

### ISSUE THREAD

**Issue by DylanPiercey** [angus-c/just#46]
Great list of modules here. I think it would be a good idea to switch to [scoped modules](https://docs.npmjs.com/misc/scope) with a [public org](https://www.npmjs.com/docs/orgs/).

There are several benefits here:

1) There is no chance that someone could steal a package name.
2) Users can more trust `just` packages without worrying about squaters/malware.
3) You can more easily give other developers access/control of individual repo's and manage it all from one org.

The only problem is that [just](https://www.npmjs.com/package/just) is taken. Luckily it's a squated package with no docs and hasn't been updated for 5 years. You should have no issue retrieving this if you email NPM, but it can take some time.

**Comment by angus-c** [comment]
is it possible to alias to the current location so existing users' apps won't break?

**Comment by DylanPiercey** [comment]
Not that I’m aware of. I suppose you could technically have two folders for all repos and use Lerna to publish under the old name and new name in lock step.

**Comment by angus-c** [comment]
Closing for now since, although I like the idea, I don't yet know of a way to easily alias to old location.
