### ISSUE TITLE
just-compare types don't work with generics

### ISSUE THREAD

**Issue by dimfeld** [angus-c/just#460]
There doesn't seem to be a way to use generic types as inputs to `just-compare`.

[Typescript Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAYwuAhlApnAZlZcDkAVgK4DOMAtEqhvgNwBQDWxAdgjMBK4smGugCSMADwAVOOgAeMdKwAmpOAG8A+sHkAuOOSjBWAcwC+APgAU3dNrEAaODADuEawEoVDOJ7gYYxKD2p+DAtWdDtHCBdGIyA)

```ts
import compare from 'just-compare';

function compareIt<DATA extends {_id: string}>(one: DATA, two: DATA) {
    return compare(one, two);
}
```

Typescript doesn't seem to like `Exclude<DATA, Primitive>` in this case. This example fails with a similar error:

```ts
/* Fails with:
Type 'T' is not assignable to type 'Exclude<T, null>'.
Type '{ _id: string; }' is not assignable to type 'Exclude<T, null>'.
*/
function compareIt<T extends {_id: string}>(one: T, two: T) {
  type NonNulled = Exclude<T, null>; // Excluding number, string, etc. also throws the error
  const a: NonNulled = one;
}
```

I think altering the `just-compare` definitions on the second and third definitions to change `Exclude<T, Primitive>` to just `T` will fix this, without removing type safety since the type constraints are already checking for `T1` or `T2` to `extends object`.

What do you think? I'm happy to submit a PR if this sounds ok to you.

**Comment by angus-c** [comment]
Sounds good. Yes I'd appreciate a PR, thanks!
