### ISSUE TITLE
Make compatible with TS 4.7

### ISSUE THREAD

**Issue by angus-c** [angus-c/just#468]
Add `"types": "./index.d.ts"` to every package.json `exports` dot property

See https://github.com/angus-c/just/pull/429#issuecomment-1097174234
Existing issue: https://github.com/angus-c/just/issues/428

**Comment by benasher44** [comment]
Would contributions here still be helpful? Happy to open a PR!

**Comment by angus-c** [comment]
Yes please!

**Comment by benasher44** [comment]
Took a slightly different approach and instead took this all a step closer to being more ESM-ready in #489

**Comment by angus-c** [comment]
Thanks Ben! Going to have to do some thorough testing so might not get to this until at least next weekend

**Comment by benasher44** [comment]
No problem. Thank you!

**Comment by benasher44** [comment]
After the latest updates (guessing #488), the packages are now usable by doing `import { default as <x> } from "just-<x>";`. The open PR would still improve things for NodeNext users, but at least now there is a path forward!

**Comment by angus-c** [comment]
Fixed by https://github.com/angus-c/just/pull/489
