### ISSUE TITLE
'pipe' function

### ISSUE THREAD

**Issue by TClark1011** [angus-c/just#475]
- **Flow:** A left-to-right version of `compose`
- **Pipe:** A version of `flow`, except instead of returning a new function, the first parameter is passed through the composed function and the end result is returned

Reference: https://mobily.github.io/ts-belt/api/pipe-flow

**Comment by angus-c** [comment]
I like both of these. PRs welcome of I don't get to it myself.

**Comment by TClark1011** [comment]
I'm happy to do it, is there any particular procedure for creating new modules?

**Comment by TClark1011** [comment]
I actually just realised that `just-compose` already uses left-to-right function composition, so `flow` is irrelevant. Sorry about that, I'm just so used to `compose` using right-to-left composition that I didn't even check. I'm still happy to create `pipe` however

**Comment by angus-c** [comment]
Ha no my bad. I wrote it so long ago I forgot :) 
[Here are the guidelines](https://github.com/angus-c/just/blob/master/CONTRIBUTING.md) for creating new modules

**Comment by angus-c** [comment]
Closed by https://github.com/angus-c/just/pull/492
