### ISSUE TITLE
`omit` typing?

### ISSUE THREAD

**Issue by aradalvand** [angus-c/just#495]
Hi there, thanks for this immensely useful library.

The current signature of the `omit` function is as follows:

```ts
function omit<Obj extends object, Key extends string>(obj: Obj, remove: Key[]): Omit<Obj, Key>;
```

This doesn't make sense, it means that you get no type-safety whatsoever when specifying the property keys, they would effectively be magic strings. Why not:

```ts
function omit<T extends object>(obj: T, remove: (keyof T)[]);
```

This, on the other hand, does provide type-safety and all the goodness that comes with it (e.g. code completion, etc.)

**Comment by Masa-Shin** [comment]
Thanks, I will fix this.

**Comment by Masa-Shin** [comment]
Now I remember why the type definition is like that. In the example of the package you can find `omit(obj, ['a', 'b', 'd']); // {c: 9}`, where `d` is not a key of `obj`.

**Comment by aradalvand** [comment]
@Masa-Shin Then why isn't `pick` like that? They at least have to be consistent, don't they?

`pick`'s signature looks like this:
```ts
function pick<T, U extends keyof T>(obj: T, select: U[]): Pick<T, U>;
```

And there's also an example like the one you mentioned for `pick` [here](https://github.com/angus-c/just#just-pick):
```js
pick(obj, ['a', 'b', 'd']); // {a: 3, b: 5}
```
This example actually yields an error:

![image](https://user-images.githubusercontent.com/26527405/189319072-e7cb7138-6989-41ee-9ecd-20d66d566cf3.png)


So these two functions need to be consistent at the very least.
But I would argue `omit` should become like `pick` and not the other way around, because `omit` now essentially provides zero type-safety and that's not good, if somebody wants to add a property to the second argument that doesn't exist in the type, they would use type inference:

![image](https://user-images.githubusercontent.com/26527405/189319510-d5948923-570d-4cd2-93cb-9f7bc13d0118.png)

This is actually how you handle edge cases like this in TypeScript. The library, however, should provide the right typing.

**Comment by Masa-Shin** [comment]
I see your point. I made `omit`'s typing reflect the actual behavior of the function for the convenience of those who already using it (as they may have passed arbitrary lists of string to it), but I realized that people using TS may be looking for safety over convenience so now I rather agree with your suggestion.

**Comment by Masa-Shin** [comment]
I think it is OK to make a PR for the issue since that for the `pick` has already been merged. I will make a PR If it is OK with you.

**Comment by aradalvand** [comment]
> but I realized that people using TS may be looking for safety over convenience

Yes, exactly!

> I think it is OK to make a PR for the issue since that for the pick has already been merged. If it is OK with you, I will do it today.

Yeah I think that makes sense, that would be great, thank you so much! :)

**Comment by angus-c** [comment]
Thanks @aradalvand and @Masa-Shin! PR landed
