### ISSUE TITLE
just-clone does not maintain class inheritance

### ISSUE THREAD

**Issue by blumewas** [angus-c/just#506]
Hi,

it seems like that 'just-clone' does not maintain the class for objects created via `new classes`.

E.g.:

```js
const clone = require('just-clone');

class Foo {
    constructor(bar) {
        this.bar = bar;
    }
}

const arr = [new Foo('test1'), new Foo('test2')];

const cloneArr = clone(arr);

console.log(arr[0] instanceof Foo); // true
console.log(cloneArr[0] instanceof Foo); // false
```

It would be great if clone would support objects created from classes. If you would like to keep the speed of the function there might be room for a slower function which keeps this inheritance.

**Comment by angus-c** [comment]
Closing as out of scope of this util
