### ISSUE TITLE
just-percentile throws ‘The percent must be between 0 and 1 when percentage argument value is less then 0 or greater than 1

### ISSUE THREAD

**Issue by jitendrakhodani** [angus-c/just#508]
just-percentile throws ‘The percent must be between 0 and 1 when percentage argument value is less than 0 or greater than 1 at line number 11 https://github.com/angus-c/just/blob/4636c2c6b6df2500df5217f579818283916d2215/packages/array-percentile/index.js#L11

However, examples in documentation for just-percentile shows percentile method accepts values greater than 1.

percentile([1, 2, 3], 50); // 2
percentile([1, 2, 3], 100); // 3

Either we can fix the documentation or we can change the implementation of the method.

**Comment by angus-c** [comment]
Good call! The documentation is wrong. I will fix it.

**Comment by angus-c** [comment]
Fixed!
