### ISSUE TITLE
just-diff fails on array or object with null member value

### ISSUE THREAD

**Issue by rereadyou** [angus-c/just#51]
const {diff, jsonPatchPathConverter} = require('just-diff')

diff(
{a: 'a', b:null, c:'b'},
{a: 'a', b:'b'},
  /* jsonPatchPathConverter */
);

result in: 
Array (2 items)
0: Object
op: "remove"
path: ["c"]
1: Object
op: "add"
path: ["b"]
value: "b"

should it be: 
Array (2 items)
0: Object
op: "remove"
path: ["c"]
1: Object
op: "replace"
path: ["b"]
value: "b"

**Comment by angus-c** [comment]
good catch - will fix tonight

**Comment by angus-c** [comment]
should be fixed now
* just-diff v2.0.2
* just-diff-apply v1.0.1
