### ISSUE TITLE
just-safe-set docs do not agree with implementation

### ISSUE THREAD

**Issue by Daniel-Pierce-IV** [angus-c/just#533]
safe-set is supposed to avoid "clobbering" objects when setting a prop that has nested object within it (I assume). This functionality does not exist, even when using the exact example from the documentation.

See: https://github.com/angus-c/just/blob/master/packages/object-safe-set/index.cjs#L16

**Comment by angus-c** [comment]
Yes sorry the documentation is wrong. (Lodash _.set also clobbers in the same way)
Thanks for spotting this, I will fix.

**Comment by angus-c** [comment]
Fixed in just-safe-set@4.2.1
