### ISSUE TITLE
Switch to typescript.

### ISSUE THREAD

**Issue by DylanPiercey** [angus-c/just#66]
@angus-c not sure if you are a fan of typescript but I think it's worth considering converting 'just' packages to use it.

Primarily this would be great for users as it would bring autocompletion for VSCode (or atom with plugin) with inline docs. You can also achieve this by creating 'typings' files however there are many other advantages to using typescript.

If you are interested in this I'd be willing to lend a hand setting up the scripts and converting the modules (I've recently started doing this with some of my own modules).

Just thought I'd gauge your interest in this idea.

**Comment by angus-c** [comment]
Hi Dylan, I'm not a huge TypeScript fan, (though mainly because I've never used it for a proper project). Appreciate the offer of help but I think I'll pass on it for now (would like to avoid the transpile step and associated size increase too)

**Comment by DylanPiercey** [comment]
Fair enough, just thought I'd bring it up. If you ever do want to checkout typescript for a module checkout [one of my smaller modules](https://github.com/DylanPiercey/header-field) for a clean setup 😄. The hardest part of getting in for me was getting that base config right.
