### ISSUE TITLE
object-extend does not work with dates

### ISSUE THREAD

**Issue by pavvell** [angus-c/just#77]
object-extend converts dates in merged object into empty object.
Is that on purpose, such simplicity of the function?

**Comment by angus-c** [comment]
yeah it works with shallow copy

```js
var x = extend({}, {a: new Date()});
x.a; // date
```

but not with deep copy
```js
var x = extend(true, {}, {a: new Date()});
x.a; // {}
```

this is because deep copy assumes that objects being cloned is an array or a plain object. I should make it check for date, regex etc and simply not clone these.
