### ISSUE TITLE
Allow undefined in just-extend

### ISSUE THREAD

**Issue by ritz078** [angus-c/just#83]
Going in the lines with `Object.assign()`, `undefined` should be allowed as an argument. 

**Actual Behavior**

```js
const x = extend({}, {a:'x'}, undefined) //throws error
 ```

**Expected Behaviour**

```js
const x = extend({}, {a:'x'}, undefined) //{a: "x"}  
```

**lodash**

```js
const x = _.assignIn({}, {a: 'x'}, undefined) //{a: "x"}
```

**Object.assign**

```js
const x = Object.assign({}, {a: 'x'}, undefined) //{a: "x"}
```

Most of the times, I will be using it as a polyfill for `Object.assign` so I really will want `just-extend` to have an API similar to it?

**Comment by angus-c** [comment]
Hi Ritesh.

I believe this works as of 1.1.27. See http://anguscroll.com/just/just-extend.

Please confirm this works for you.

**Comment by ritz078** [comment]
Yes, it is working great. Thanks for this awesome collection of utilities. :)

**Comment by angus-c** [comment]
Thanks for using them! Happy to consider any future feature requests.
