### ISSUE TITLE
default export diff and diffApply

### ISSUE THREAD

**Issue by rikur** [angus-c/just#92]
First of all: Thank you for the collection, this is just what I needed!

There's a slight inconsistency on the module exports. All other utils have a default export except for diff and diffApply. It should be trivial fix this without breaking existing use of the libraries.

```
import diff from 'just-diff'
```

could and should be supported alongside with

```
import { diff } from 'just-diff'
```

Let me know what you think. I can create a PR if you agree.

**Comment by angus-c** [comment]
Thanks for the kind words!

Sounds good. (I honestly don't know how to have node module.export both a top level object and properties other than `module.exports = diff` and then add the `jsonPatchPathConverter` property to `diff`

**Comment by angus-c** [comment]
Hi @rikur. Happy to keep this open if a PR is pending. Otherwise I'd like to close to keep a clean house.

**Comment by rikur** [comment]
Oh, sorry. I'm closing it now. I'll submit a PR when I find the moment.
